import { Player } from "@/types";

export const MOCK_PLAYERS: Player[] = [
  {
    id: "p1",
    name: "Ahmet Yılmaz",
    avatar: "🧤",
    ratings: { GK: 88, DEF: 62, MID: 55, FWD: 48 },
    position: { primary: "GK", secondary: "DEF" },
  },
  {
    id: "p2",
    name: "Mehmet Kaya",
    avatar: "🛡️",
    ratings: { GK: 58, DEF: 84, MID: 72, FWD: 65 },
    position: { primary: "DEF", secondary: "MID" },
  },
  {
    id: "p3",
    name: "Ali Demir",
    avatar: "⚙️",
    ratings: { GK: 45, DEF: 79, MID: 86, FWD: 74 },
    position: { primary: "MID", secondary: "DEF" },
  },
  {
    id: "p4",
    name: "Can Öztürk",
    avatar: "⚡",
    ratings: { GK: 40, DEF: 68, MID: 81, FWD: 89 },
    position: { primary: "FWD", secondary: "MID" },
  },
  {
    id: "p5",
    name: "Burak Şahin",
    avatar: "🛡️",
    ratings: { GK: 52, DEF: 82, MID: 75, FWD: 70 },
    position: { primary: "DEF" },
  },
  {
    id: "p6",
    name: "Emre Aydın",
    avatar: "⚙️",
    ratings: { GK: 42, DEF: 71, MID: 88, FWD: 78 },
    position: { primary: "MID", secondary: "FWD" },
  },
  {
    id: "p7",
    name: "Deniz Arslan",
    avatar: "⚡",
    ratings: { GK: 38, DEF: 65, MID: 76, FWD: 85 },
    position: { primary: "FWD" },
  },
  {
    id: "p8",
    name: "Furkan Çelik",
    avatar: "⚙️",
    ratings: { GK: 44, DEF: 74, MID: 83, FWD: 80 },
    position: { primary: "MID", secondary: "DEF" },
  },
  {
    id: "p9",
    name: "Serkan Yıldız",
    avatar: "🧤",
    ratings: { GK: 82, DEF: 60, MID: 58, FWD: 50 },
    position: { primary: "GK" },
  },
  {
    id: "p10",
    name: "Oğuz Karaca",
    avatar: "🛡️",
    ratings: { GK: 48, DEF: 77, MID: 80, FWD: 72 },
    position: { primary: "DEF", secondary: "MID" },
  },
  {
    id: "p11",
    name: "Kerem Polat",
    avatar: "⚡",
    ratings: { GK: 35, DEF: 63, MID: 79, FWD: 91 },
    position: { primary: "FWD", secondary: "MID" },
  },
  {
    id: "p12",
    name: "Tolga Erdoğan",
    avatar: "⚙️",
    ratings: { GK: 41, DEF: 69, MID: 85, FWD: 77 },
    position: { primary: "MID" },
  },
  {
    id: "p13",
    name: "Barış Koç",
    avatar: "🛡️",
    ratings: { GK: 50, DEF: 80, MID: 73, FWD: 68 },
    position: { primary: "DEF", secondary: "FWD" },
  },
  {
    id: "p14",
    name: "Umut Güneş",
    avatar: "⚡",
    ratings: { GK: 36, DEF: 61, MID: 74, FWD: 87 },
    position: { primary: "FWD" },
  },
  {
    id: "p15",
    name: "Cem Aksoy",
    avatar: "🧤",
    ratings: { GK: 76, DEF: 58, MID: 62, FWD: 55 },
    position: { primary: "GK", secondary: "DEF" },
  },
  {
    id: "p16",
    name: "Hakan Tekin",
    avatar: "⚙️",
    ratings: { GK: 43, DEF: 72, MID: 84, FWD: 75 },
    position: { primary: "MID", secondary: "DEF" },
  },
];
